### ISSUE TITLE
[Bug Report] Incorrect Podcast File Suffix and Not Detecting Existing Files

### ISSUE THREAD

**Issue by Ragnaran** [Googolplexed0/zotify#53]
Downloading podcasts results in failures.  The ffmpeg stream identification routine is appending `\n STREAM` to the resulting codec name, causing the EXT_MAP to fail and the file not being found.

This PR solves it: https://github.com/Googolplexed0/zotify/pull/52

Note that existing files are not being correctly checked correctly, so the podcast is being downloaded again, every time, even if it already exists.  This is a slightly different issue that I haven't had a chance to investigate yet.

(I appreciate the effort to actually identify the codec!  I'd bet a steak dinner that all podcasts are encoded in vorbis, but who knows if that will ever change?)

**Comment by Googolplexed0** [comment]
Both issues should now be fixed. Thanks for the bug find and fix!

**Comment by Ragnaran** [comment]
Sadly, duplicates are still getting ignored.  The logic `episode_path_exists = Path(episode_path).is_file()` is using the `path + ".tmp"` file name + the file size.  A successfully downloaded file gets moved to the extension, so it won't have a `.tmp` extension, so the duplication check will never succeed.  That's while I tried iterating against files that might have the extension in the EXT_MAP.

I'll see if I can fix it.

**Comment by Ragnaran** [comment]
I nailed it down.  I believe the `stream.input_stream.size` might be reported in 1024 increment chunks, while on-disk file sizes might not reach that.  I've added a check to allow the on-disk filesize to be up to 1024 bytes smaller.

The problem with .glob() (in my opinion) is that it wouldn't account for multiple matching files, or files that got copied/renamed.  

Anyhoo, I've tested https://github.com/Googolplexed0/zotify/pull/59 successfully.

**Comment by Googolplexed0** [comment]
> The problem with .glob() (in my opinion) is that it wouldn't account for multiple matching files, or files that got copied/renamed.

This isn't an issue with `.glob()`? There is no way to implement duplicate detection based on a filename pattern that would account for files that have been renamed. This would require checking against something other than filenames by definition. Also not sure what you mean by multiple matching files. The only part that is wildcarded in the `.glob()` is the file suffix, which accounts for the error cases where the file suffix exists outside of the EXT_MAP.

> I've added a check to allow the on-disk filesize to be up to 1024 bytes smaller

I do like this idea overall though. Will implement something similar.
